import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TRPCSetupProvider } from "./_trpc/TRPCSetupProvider";
import { CookiesProvider } from "next-client-cookies/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CookiesProvider>
          <TRPCSetupProvider>{children}</TRPCSetupProvider>
        </CookiesProvider>
      </body>
    </html>
  );
}
